name: ci

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    environment:
      name: ci
      deployment: false

    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - windows-latest
          - ubuntu-latest

    env:
      NODE_VERSION: 24
      PNPM_VERSION: 10
      FLATPAK_RUNTIME_VERSION: "25.08"

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
          fetch-depth: 1

      - name: Setup pnpm
        uses: pnpm/action-setup@26f6d4f2c533a43e6b5da0b4a5dd983f98f7b49a # v6
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update -y
          sudo apt-get install --no-install-recommends -y \
            flatpak \
            flatpak-builder \
            libopenjp2-tools \
            rpm \
            libarchive-tools

      - name: Install Flatpak runtimes
        if: runner.os == 'Linux'
        run: |
          flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          flatpak install --user --noninteractive flathub org.freedesktop.Platform//${{ env.FLATPAK_RUNTIME_VERSION }}
          flatpak install --user --noninteractive flathub org.freedesktop.Sdk//${{ env.FLATPAK_RUNTIME_VERSION }}
          flatpak install --user --noninteractive flathub org.electronjs.Electron2.BaseApp//${{ env.FLATPAK_RUNTIME_VERSION }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run dist --publish never

      - name: Build Flatpak
        if: runner.os == 'Linux'
        run: pnpm exec electron-builder --config electron-builder.config.js --linux flatpak --publish never

      - name: Upload build
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: ${{ matrix.os }}-${{ env.NODE_VERSION }}
          path: ./dist

      - name: Upload Flatpak
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: flatpak
          path: dist/*.flatpak          